sudo: required
dist: trusty
language: cpp
compiler: gcc
notifications:
        email: false
addons:
        apt:
                packages:
                - libmusicbrainz5-dev
                - libtag1-dev
before_install:
- wget -O boost_1_60_0.tar.bz2 https://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.bz2/download
- tar --bzip2 -xf boost_1_60_0.tar.bz2 && cd boost_1_60_0
- ./bootstrap.sh --prefix=/usr/local --with-libraries=filesystem,system,program_options,test
- ./b2 -j2 -d0
- sudo ./b2 -d0 install
- cd ..
script:
- mkdir build && cd build
- cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON .. && make -j2 && make test
after_failure:
- for file in bin/tests/*; do echo $file; $file; echo "======="; done
