sudo: required
dist: trusty
language: cpp
compiler: gcc
addons:
        apt:
                packages:
                - libboost-system-dev
                - libboost-filesystem-dev
                - libboost-program-options-dev
                - libboost-test-dev
                - libmusicbrainz4-dev
                - libtag1-dev
script:
- mkdir build && cd build
- cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON .. && make -j2 && make test
