name: Build, Test and Coverage
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y libmusicbrainz5-dev libtag1-dev libpugixml-dev

      - name: Download Boost
        run: wget -O boost_1_79_0.tar.bz2 https://sourceforge.net/projects/boost/files/boost/1.79.0/boost_1_79_0.tar.bz2/download

      - name: Unpack Boost
        run: tar --bzip2 -xf boost_1_79_0.tar.bz2

      - name: Build and install Boost
        working-directory: ./boost_1_79_0
        run: |
          ./bootstrap.sh --prefix=/usr/local --with-libraries=filesystem,system,program_options,test
          ./b2 -d0
          sudo ./b2 -d0 install
          sudo ldconfig

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=ON

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: make

      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: make test
